/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISocialNodeRegistry,
  ISocialNodeRegistryInterface,
} from "../../../../contracts/core/WasteSettlement.sol/ISocialNodeRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "node",
        type: "address",
      },
    ],
    name: "isSocialNode",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ISocialNodeRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): ISocialNodeRegistryInterface {
    return new utils.Interface(_abi) as ISocialNodeRegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISocialNodeRegistry {
    return new Contract(address, _abi, signerOrProvider) as ISocialNodeRegistry;
  }
}
