/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IWasteToken,
  IWasteTokenInterface,
} from "../../../../contracts/core/WasteSettlement.sol/IWasteToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IWasteToken__factory {
  static readonly abi = _abi;
  static createInterface(): IWasteTokenInterface {
    return new utils.Interface(_abi) as IWasteTokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWasteToken {
    return new Contract(address, _abi, signerOrProvider) as IWasteToken;
  }
}
