/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IWasteDataProvider,
  IWasteDataProviderInterface,
} from "../../../../contracts/core/WasteSettlement.sol/IWasteDataProvider";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "wasteTypeId",
        type: "string",
      },
    ],
    name: "getCarbonEmissionRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IWasteDataProvider__factory {
  static readonly abi = _abi;
  static createInterface(): IWasteDataProviderInterface {
    return new utils.Interface(_abi) as IWasteDataProviderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWasteDataProvider {
    return new Contract(address, _abi, signerOrProvider) as IWasteDataProvider;
  }
}
