/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IWastePriceProvider,
  IWastePriceProviderInterface,
} from "../../../../contracts/core/WasteSettlement.sol/IWastePriceProvider";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "wasteTypeId",
        type: "string",
      },
    ],
    name: "getWastePrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IWastePriceProvider__factory {
  static readonly abi = _abi;
  static createInterface(): IWastePriceProviderInterface {
    return new utils.Interface(_abi) as IWastePriceProviderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWastePriceProvider {
    return new Contract(address, _abi, signerOrProvider) as IWastePriceProvider;
  }
}
