/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISocialNodeRegistry } from "./ISocialNodeRegistry";
export type { IWasteDataProvider } from "./IWasteDataProvider";
export type { IWastePriceProvider } from "./IWastePriceProvider";
export type { IWasteToken } from "./IWasteToken";
export type { WasteSettlement } from "./WasteSettlement";
