/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SocialNodeRegistry } from "./SocialNodeRegistry";
export type { WasteDataProvider } from "./WasteDataProvider";
export type { WastePriceProvider } from "./WastePriceProvider";
