/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as wasteSettlementSol from "./WasteSettlement.sol";
export type { wasteSettlementSol };
export type { SocialNodeRegistry } from "./SocialNodeRegistry";
export type { USDC } from "./USDC";
export type { WasteDataProvider } from "./WasteDataProvider";
export type { WastePriceProvider } from "./WastePriceProvider";
export type { WasteToken } from "./WasteToken";
