/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as wasteSettlementSol from "./WasteSettlement.sol";
export { SocialNodeRegistry__factory } from "./SocialNodeRegistry__factory";
export { USDC__factory } from "./USDC__factory";
export { WasteDataProvider__factory } from "./WasteDataProvider__factory";
export { WastePriceProvider__factory } from "./WastePriceProvider__factory";
export { WasteToken__factory } from "./WasteToken__factory";
