/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SocialNodeRegistry__factory } from "./SocialNodeRegistry__factory";
export { WasteDataProvider__factory } from "./WasteDataProvider__factory";
export { WastePriceProvider__factory } from "./WastePriceProvider__factory";
