/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as core from "./core";
export type { core };
import type * as sample from "./sample";
export type { sample };
export * as factories from "./factories";
export type { SocialNodeRegistry } from "./core/SocialNodeRegistry";
export { SocialNodeRegistry__factory } from "./factories/core/SocialNodeRegistry__factory";
export type { Storage } from "./sample/Storage";
export { Storage__factory } from "./factories/sample/Storage__factory";
