/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SocialNodeRegistry } from "./SocialNodeRegistry";
export type { WasteDataProvider } from "./WasteDataProvider";
export * as factories from "./factories";
export { SocialNodeRegistry__factory } from "./factories/SocialNodeRegistry__factory";
export { WasteDataProvider__factory } from "./factories/WasteDataProvider__factory";
